name: Build Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: makeP1
      run: cd src && javac P1/P1.java
    - name: runP1
      run: cd src && java P1/P1 P1/P1-1in.txt 5
    - name: makeP2
      run: cd src && javac P2/P2.java
    - name: runP2
      run: cd src && java P2/P2 P2/P2-1in.txt
    - name: makeP3
      run: cd src && javac P3/P3.java
    - name: runP3
      run: cd src && java P3/P3 P3/P2-1in.txt
